biblioteca/urls.py
from django.conf.urls import url
from biblioteca import views

editor_functions_crud = [
    url(r'^editores/crear$', views.create_editor, name='create_editor'),
    url(r'^editores$', views.read_editors, name='read_editors'),
    url(r'^editores/(?P<editor_id>\d+)/update$', views.update_editor, name='update_editor'),
    url(r'^editores/(?P<editor_id>\d+)/delete$', views.delete_editor, name='delete_editor'),
]
editor_clases_crud = [
    url(r'^editores/clases/crear$', views.EditoresCreate.as_view(), name='clases_create_editor'),
    url(r'^editores/clases$', views.EditoresReadAll.as_view(), name='clases_read_all_editors'),
    url(r'^editores/clases/(?P<pk>\d+)/update$', views.EditoresUpdate.as_view(), name='clases_update_editor'),
    url(r'^editores/clases/(?P<pk>\d+)/delete$', views.EditoresDelete.as_view(), name='clases_delete_editor'),
]
author_functions_crud = [
    url(r'^autores/crear$', views.create_author, name='create_author'),
    url(r'^autores$', views.read_authors, name='read_authors'),
    url(r'^autores/(?P<author_id>\d+)/update$', views.update_author, name='update_author'),
    url(r'^autores/(?P<author_id>\d+)/delete$', views.delete_author, name='delete_author'),
]
author_clases_crud = [
    url(r'^autores/clases/crear$', views.AuthorCreate.as_view(), name='clases_create_author'),
    url(r'^autores/clases$', views.AuthorReadAll.as_view(), name='clases_read_all_author'),
    url(r'^autores/clases/(?P<pk>\d+)/update$', views.AuthorUpdate.as_view(), name='clases_update_author'),
    url(r'^autores/clases/(?P<pk>\d+)/delete$', views.AuthorDelete.as_view(), name='clases_delete_author'),
]
book_functions_crud = [
    url(r'^libros/crear$', views.create_book, name='create_book'),
    url(r'^libros$', views.read_books, name='read_books'),
    url(r'^libros/(?P<book_id>\d+)/update$', views.update_book, name='update_book'),
    url(r'^libros/(?P<book_id>\d+)/delete/$', views.delete_book, name='delete_book'),
]
book_clases_crud = [
    url(r'^libros/clases/crear$', views.BookCreate.as_view(), name='clases_create_book'),
    url(r'^libros/clases$', views.BookReadAll.as_view(), name='clases_read_all_books'),
    url(r'^libros/clases/(?P<pk>\d+)/update', views.BookUpdate.as_view(), name='clases_update_book'),
    url(r'^libros/clases/(?P<pk>\d+)/delete$', views.BookDelete.as_view(), name='clases_delete_book'),
]

editor_urls = editor_functions_crud + editor_clases_crud
author_urls = author_functions_crud + author_clases_crud
book_urls = book_functions_crud + book_clases_crud

urlpatterns = editor_urls + author_urls + book_urls

misitio/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^biblioteca/', include('biblioteca.urls', namespace='biblioteca')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    {% block extrahead %}
        <link rel="stylesheet" href="{% static 'css/utity-clases.css' %}"/>
    {% endblock %}
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %} Biblioteca CRUD {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
</head>
<body>
{% block header %} {% include 'base/header.html' %} {% endblock %}

<div class="container">
    {% block content %}  {% endblock %}
</div>

{% block footer %}  {% endblock %}


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://bootswatch.com/_vendor/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
{% block extrajs %}  {% endblock %}
</body>
</html>

templates/base/header.html
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">WISPHUB</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03"
                    aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor03">
                <ul class="navbar-nav w-100">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-uppercase" data-bs-toggle="dropdown" href="#"
                           role="button" aria-haspopup="true" aria-expanded="false">
                            Editores
                        </a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'biblioteca:read_editors' %}">Listar (función)</a>
                            <a class="dropdown-item" href="{% url 'biblioteca:create_editor' %}">Registrar (función)</a>
                            <a class="dropdown-item" href="{% url 'biblioteca:clases_read_all_editors' %}">
                                Listar (clases)
                            </a>
                            <a class="dropdown-item" href="{% url 'biblioteca:clases_create_editor' %}">
                                Registrar (clases)
                            </a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-uppercase" data-bs-toggle="dropdown" href="#"
                           role="button"
                           aria-haspopup="true" aria-expanded="false">
                            Autores
                        </a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'biblioteca:read_authors' %}">Listar (función)</a>
                            <a class="dropdown-item" href="{% url 'biblioteca:create_author' %}">Registrar (función)</a>
                            <a class="dropdown-item" href="{% url 'biblioteca:clases_read_all_author' %}">
                                Listar (clases)
                            </a>
                            <a class="dropdown-item" href="{% url 'biblioteca:clases_create_author' %}">
                                Registrar (clases)
                            </a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-uppercase" data-bs-toggle="dropdown" href="#"
                           role="button"
                           aria-haspopup="true" aria-expanded="false">
                            Libros
                        </a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'biblioteca:read_books' %}">Listar(función)</a>
                            <a class="dropdown-item" href="{% url 'biblioteca:create_book' %}">Registrar(función)</a>
                            <a class="dropdown-item" href="{% url 'biblioteca:clases_read_all_books' %}">
                                Listar (clases)
                            </a>
                            <a class="dropdown-item" href="{% url 'biblioteca:clases_create_book' %}">
                                Registrar (clases)
                            </a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>